sudo: required
dist: trusty
language: node_js

addons:
  chrome: stable

git:
  depth: 1

cache:
  yarn: true
  directories:
    - ./node_modules/

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - export NG_CLI_ANALYTICS=ci
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - chmod +x -R scripts
  - yarn

jobs:
  include:
    - env: 'MODE=build'
    - env: 'MODE=lint'
    - env: 'MODE=test-coverage'

script:
  - ./scripts/_ci/travis.sh
